######################################################################
# Automatically generated by qmake (1.07a) Fri Mar 8 08:17:07 2013
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += ttt_qt.cpp
